---
eureka:
  #instance:
    #hostname: localhost
    #non-secure-port: ${server.port}
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8090