---
eureka:
  instance:
    hostname: localhost
    non-secure-port: 8080
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080