---
eureka:
  #instance:
  #  preferIPAddress: true
  #instance:
  #  hostname: localhost
  #  non-secure-port: ${server.port}      
  client:
    #registerWithEureka: true
    #service-url:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

spring:
  jpa:
    generate-ddl: true
      
hello:
  message: Hello from application.yml